name = "VersatileHDPMixtureModels"
uuid = "cb401d7d-c4f9-4284-af24-a1eca280e8e8"
authors = ["Or Dinari <dinari.or@gmail.com>"]
version = "0.1.1"

[deps]
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Clustering = "^0.13,0,1"
Distributions = "0, 1"
JLD2 = "0, 2"
NPZ = "0, 2"
SpecialFunctions = "0,1"
StatsBase = "0,2"
julia = "1.5,2"
PDMats ="0,1"
